Reindented.

diff --git a/git-test-sequence b/git-test-sequence
--- a/git-test-sequence
+++ b/git-test-sequence
@@ -12,16 +12,16 @@ ref_name=pass
 
 # The tree must be really really clean.
 if ! git update-index --ignore-submodules --refresh > /dev/null; then
-	echo >&2 "cannot rebase: you have unstaged changes"
-	git diff-files --name-status -r --ignore-submodules -- >&2
-	exit 1
+    echo >&2 "cannot rebase: you have unstaged changes"
+    git diff-files --name-status -r --ignore-submodules -- >&2
+    exit 1
 fi
 diff=$(git diff-index --cached --name-status -r --ignore-submodules HEAD --)
 case "$diff" in
-?*)	echo >&2 "cannot rebase: your index contains uncommitted changes"
-	echo >&2 "$diff"
-	exit 1
-	;;
+    ?*) echo >&2 "cannot rebase: your index contains uncommitted changes"
+        echo >&2 "$diff"
+        exit 1
+        ;;
 esac
 
 start_branch=`git rev-parse --symbolic-full-name HEAD | sed s,refs/heads/,,`
@@ -52,25 +52,25 @@ new_test() {
     git reset --hard $v && eval "$2" && passed_on $v || broke_on $v
     status=$?
     if test -n "$run_once"; then
-	cleanup
-	exit $status
+        cleanup
+        exit $status
     fi
 }
 
 
 while test $# != 0
 do
-    case "$1" in 
-    --once)
-        run_once=yes
-	;;
-    --ref-name)
-        ref_name=$2
-	shift
-	;;
-    *)
-        break;
-	;;
+    case "$1" in
+        --once)
+            run_once=yes
+            ;;
+        --ref-name)
+            ref_name=$2
+            shift
+            ;;
+        *)
+            break;
+            ;;
     esac
     shift
 done
